import type { Metadata } from "next";
import "./globals.css"
import { Inter } from "next/font/google";
import { Toaster } from "./components/ui/toaster"
import { QueryProvider } from "./components/providers/query-provider"
import { Providers } from "./components/ui/providers"


const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <QueryProvider>
            {children}
            <Toaster />
          </QueryProvider>
        </Providers>
      </body>
    </html>
  )
} 
