"""Add AI job matching models - UserProfile, JobScore, DailyDigest

Revision ID: 281859486997
Revises: 52127d5025ad
Create Date: 2025-07-22 12:00:45.779515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281859486997'
down_revision: Union[str, None] = '52127d5025ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_job_preferences', sa.Column('location_radius', sa.Integer(), nullable=True))
    op.add_column('user_job_preferences', sa.Column('preferred_company_sizes', sa.JSON(), nullable=True))
    op.alter_column('user_job_preferences', 'user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user_job_preferences', 'notification_frequency',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_user_job_preferences_user_id'), 'user_job_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_job_preferences_user_id'), table_name='user_job_preferences')
    op.alter_column('user_job_preferences', 'notification_frequency',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('user_job_preferences', 'user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('user_job_preferences', 'preferred_company_sizes')
    op.drop_column('user_job_preferences', 'location_radius')
    # ### end Alembic commands ###
