"""add_rss_feed_configuration_and_user_preferences_tables

Revision ID: 52127d5025ad
Revises: 2ecae132f7ca
Create Date: 2025-07-18 11:14:35.724227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52127d5025ad'
down_revision: Union[str, None] = '2ecae132f7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rss_feed_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('feed_url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('location_filter', sa.String(length=255), nullable=True),
    sa.Column('keyword_filter', sa.String(length=512), nullable=True),
    sa.Column('job_type_filter', sa.String(length=50), nullable=True),
    sa.Column('experience_filter', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('refresh_interval', sa.Integer(), nullable=True),
    sa.Column('last_refresh', sa.DateTime(), nullable=True),
    sa.Column('last_job_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rss_feed_configurations_id'), 'rss_feed_configurations', ['id'], unique=False)
    op.create_table('user_job_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('preferred_locations', sa.JSON(), nullable=True),
    sa.Column('preferred_job_types', sa.JSON(), nullable=True),
    sa.Column('preferred_experience_levels', sa.JSON(), nullable=True),
    sa.Column('required_keywords', sa.JSON(), nullable=True),
    sa.Column('excluded_keywords', sa.JSON(), nullable=True),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('max_salary', sa.Integer(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('notification_frequency', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_job_preferences_id'), 'user_job_preferences', ['id'], unique=False)
    op.add_column('job_listings', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('job_listings', sa.Column('applied_date', sa.DateTime(), nullable=True))
    op.alter_column('job_listings', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('job_listings', 'application_url',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('job_listings', 'source_url',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_job_listings_company', table_name='job_listings')
    op.drop_index('ix_job_listings_title', table_name='job_listings')
    op.drop_column('job_listings', 'job_metadata')
    op.alter_column('search_results', 'match_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_results', 'match_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('job_listings', sa.Column('job_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('ix_job_listings_title', 'job_listings', ['title'], unique=False)
    op.create_index('ix_job_listings_company', 'job_listings', ['company'], unique=False)
    op.alter_column('job_listings', 'source_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('job_listings', 'application_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('job_listings', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('job_listings', 'applied_date')
    op.drop_column('job_listings', 'skills')
    op.drop_index(op.f('ix_user_job_preferences_id'), table_name='user_job_preferences')
    op.drop_table('user_job_preferences')
    op.drop_index(op.f('ix_rss_feed_configurations_id'), table_name='rss_feed_configurations')
    op.drop_table('rss_feed_configurations')
    # ### end Alembic commands ###
