"""Add applied and extracted_date columns to job_listings

Revision ID: 75324d949dc5
Revises: 
Create Date: 2025-07-16 12:54:53.029579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75324d949dc5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_listings', sa.Column('applied', sa.Boolean(), nullable=True))
    op.add_column('job_listings', sa.Column('extracted_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_listings', 'extracted_date')
    op.drop_column('job_listings', 'applied')
    # ### end Alembic commands ###
