"""Add URL extraction support to JobApplication model

Revision ID: 821de56cfafb
Revises: 6e699aeda0ea
Create Date: 2025-07-25 15:23:39.412633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821de56cfafb'
down_revision: Union[str, None] = '6e699aeda0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('source_url', sa.String(length=1000), nullable=True))
    op.add_column('job_applications', sa.Column('extraction_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_applications', 'extraction_metadata')
    op.drop_column('job_applications', 'source_url')
    # ### end Alembic commands ###
