"""Add categorized job requirements and skills fields

Revision ID: e6c7d60b7492
Revises: enhanced_profile_fields
Create Date: 2025-10-14 18:16:44.807383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6c7d60b7492'
down_revision: Union[str, None] = 'enhanced_profile_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # This autogenerated migration included destructive cleanup for tables that
    # may not exist in fresh databases. Keep the schema changes needed by the
    # current app and make legacy cleanup idempotent.
    op.execute("DROP TABLE IF EXISTS job_contacts CASCADE")
    op.execute("DROP TABLE IF EXISTS user_settings CASCADE")
    op.execute("DROP TABLE IF EXISTS apollo_usage CASCADE")
    op.execute("DROP TABLE IF EXISTS rss_feed_configurations CASCADE")
    op.execute("DROP TABLE IF EXISTS contacts CASCADE")
    op.execute("DROP INDEX IF EXISTS idx_email_events_user_id")
    op.execute("DROP INDEX IF EXISTS idx_email_sync_logs_user_id")
    op.execute("DROP INDEX IF EXISTS idx_job_applications_user_id")
    op.execute("DROP INDEX IF EXISTS idx_referral_contacts_user_email")
    op.execute("DROP INDEX IF EXISTS idx_referral_drafts_user_job_contact")
    op.execute("DROP INDEX IF EXISTS idx_referral_analytics_date_response")
    op.execute("DROP INDEX IF EXISTS idx_referral_sent_user_date")
    op.execute("DROP INDEX IF EXISTS idx_resumes_lock_status")
    op.execute("DROP INDEX IF EXISTS idx_gmail_connections_user_id")
    op.execute("DROP INDEX IF EXISTS ix_user_gmail_connections_arcade_user_id")
    op.execute("ALTER TABLE user_gmail_connections DROP COLUMN IF EXISTS arcade_user_id")
    op.execute("DROP INDEX IF EXISTS idx_user_profiles_user_id")
    op.execute("ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS minimum_requirements TEXT")
    op.execute("ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS preferred_qualifications TEXT")
    op.execute("ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS compensation_details TEXT")
    op.execute("ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS technical_skills JSON")
    op.execute("ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS soft_skills JSON")
    op.execute("ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS benefits JSON")
    op.execute("DROP INDEX IF EXISTS idx_job_listings_user_id")
    op.execute("ALTER TABLE job_listings DROP COLUMN IF EXISTS user_id")
    op.execute("CREATE INDEX IF NOT EXISTS ix_users_id ON users (id)")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_users_user_id ON users (user_id)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('users_user_id_key', 'users', ['user_id'])
    op.create_index('idx_user_profiles_user_id', 'user_profiles', ['user_id'], unique=False)
    op.add_column('user_gmail_connections', sa.Column('arcade_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_user_gmail_connections_arcade_user_id', 'user_gmail_connections', ['arcade_user_id'], unique=True)
    op.create_index('idx_gmail_connections_user_id', 'user_gmail_connections', ['user_id'], unique=False)
    op.create_index('idx_resumes_lock_status', 'resumes', ['is_locked', 'lock_expires_at'], unique=False)
    op.create_index('idx_referral_sent_user_date', 'referral_emails_sent', ['user_id', sa.text('sent_at DESC')], unique=False)
    op.create_index('idx_referral_analytics_date_response', 'referral_emails_sent', ['sent_at', 'response_received'], unique=False)
    op.create_index('idx_referral_drafts_user_job_contact', 'referral_email_drafts', ['user_id', 'job_id', 'contact_id'], unique=False)
    op.create_index('idx_referral_contacts_user_email', 'referral_contacts', ['user_id', 'contact_email'], unique=False)
    op.add_column('job_listings', sa.Column('user_id', sa.VARCHAR(length=100), server_default=sa.text("'demo_user'::character varying"), autoincrement=False, nullable=True))
    op.create_index('idx_job_listings_user_id', 'job_listings', ['user_id'], unique=False)
    op.drop_column('job_listings', 'benefits')
    op.drop_column('job_listings', 'soft_skills')
    op.drop_column('job_listings', 'technical_skills')
    op.drop_column('job_listings', 'compensation_details')
    op.drop_column('job_listings', 'preferred_qualifications')
    op.drop_column('job_listings', 'minimum_requirements')
    op.create_index('idx_job_applications_user_id', 'job_applications', ['user_id'], unique=False)
    op.create_index('idx_email_sync_logs_user_id', 'email_sync_logs', ['user_id'], unique=False)
    op.create_index('idx_email_events_user_id', 'email_events', ['user_id'], unique=False)
    op.add_column('contacts', sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('apollo_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('seniority', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('specializations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('contacts', sa.Column('linkedin_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('idx_contacts_type', 'contacts', ['type'], unique=False)
    op.create_index('idx_contacts_email', 'contacts', ['email'], unique=False)
    op.create_index('idx_contacts_created_at', 'contacts', ['created_at'], unique=False)
    op.create_index('idx_contacts_company', 'contacts', ['company'], unique=False)
    op.create_index('idx_contacts_apollo_id', 'contacts', ['apollo_id'], unique=False)
    op.create_unique_constraint('contacts_apollo_id_key', 'contacts', ['apollo_id'])
    op.alter_column('contacts', 'company',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('contacts', 'id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.create_table('rss_feed_configurations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('feed_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('location_filter', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('keyword_filter', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('job_type_filter', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('experience_filter', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('refresh_interval', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_refresh', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_job_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=100), server_default=sa.text("'demo_user'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='rss_feed_configurations_pkey')
    )
    op.create_index('ix_rss_feed_configurations_id', 'rss_feed_configurations', ['id'], unique=False)
    op.create_index('idx_rss_feeds_user_id', 'rss_feed_configurations', ['user_id'], unique=False)
    op.create_table('apollo_usage',
    sa.Column('date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('calls_made', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('calls_remaining', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('600'), autoincrement=False, nullable=True),
    sa.Column('last_reset', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('date', name='apollo_usage_pkey')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email_notifications', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notification_frequency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email_forwarding_enabled', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('forwarding_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_email_check', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('data_retention_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analytics_enabled', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='user_settings_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name='user_settings_pkey')
    )
    op.create_index('ix_user_settings_user_id', 'user_settings', ['user_id'], unique=False)
    op.create_table('job_contacts',
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('relevance_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='job_contacts_contact_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_listings.id'], name='job_contacts_job_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'contact_id', name='job_contacts_pkey')
    )
    op.create_index('idx_job_contacts_job_id', 'job_contacts', ['job_id'], unique=False)
    op.create_index('idx_job_contacts_contact_id', 'job_contacts', ['contact_id'], unique=False)
    # ### end Alembic commands ###
