// Popular cities and locations for auto-complete
export const POPULAR_LOCATIONS = [
    // Major US Cities
    "New York, NY",
    "Los Angeles, CA",
    "Chicago, IL",
    "Houston, TX",
    "Phoenix, AZ",
    "Philadelphia, PA",
    "San Antonio, TX",
    "San Diego, CA",
    "Dallas, TX",
    "San Jose, CA",
    "Austin, TX",
    "Jacksonville, FL",
    "Fort Worth, TX",
    "Columbus, OH",
    "Charlotte, NC",
    "San Francisco, CA",
    "Indianapolis, IN",
    "Seattle, WA",
    "Denver, CO",
    "Washington, DC",
    "Boston, MA",
    "El Paso, TX",
    "Nashville, TN",
    "Detroit, MI",
    "Oklahoma City, OK",
    "Portland, OR",
    "Las Vegas, NV",
    "Memphis, TN",
    "Louisville, KY",
    "Baltimore, MD",
    "Milwaukee, WI",
    "Albuquerque, NM",
    "Tucson, AZ",
    "Fresno, CA",
    "Sacramento, CA",
    "Mesa, AZ",
    "Kansas City, MO",
    "Atlanta, GA",
    "Long Beach, CA",
    "Colorado Springs, CO",
    "Raleigh, NC",
    "Miami, FL",
    "Virginia Beach, VA",
    "Omaha, NE",
    "Oakland, CA",
    "Minneapolis, MN",
    "Tulsa, OK",
    "Arlington, TX",
    "Tampa, FL",

    // Tech Hubs
    "San Francisco Bay Area, CA",
    "Silicon Valley, CA",
    "Seattle, WA",
    "Austin, TX",
    "Denver, CO",
    "Boston, MA",
    "New York, NY",
    "Los Angeles, CA",
    "Chicago, IL",
    "Atlanta, GA",
    "Dallas, TX",
    "Phoenix, AZ",
    "Portland, OR",
    "Salt Lake City, UT",
    "Raleigh-Durham, NC",
    "Nashville, TN",
    "Columbus, OH",
    "Kansas City, MO",
    "Minneapolis, MN",
    "Detroit, MI",

    // Remote Options
    "Remote",
    "Remote (US)",
    "Remote (Global)",
    "Hybrid",
    "Work from Home",

    // International Tech Hubs
    "Toronto, ON, Canada",
    "Vancouver, BC, Canada",
    "London, UK",
    "Berlin, Germany",
    "Amsterdam, Netherlands",
    "Dublin, Ireland",
    "Zurich, Switzerland",
    "Stockholm, Sweden",
    "Copenhagen, Denmark",
    "Tel Aviv, Israel",
    "Singapore",
    "Sydney, Australia",
    "Melbourne, Australia",
    "Tokyo, Japan",
    "Seoul, South Korea",
    "Bangalore, India",
    "Mumbai, India",
    "Hyderabad, India",
    "Pune, India",
    "Gurgaon, India",
    "Chennai, India",

    // Additional US Cities
    "Orlando, FL",
    "San Juan, PR",
    "Norfolk, VA",
    "Richmond, VA",
    "Buffalo, NY",
    "Rochester, NY",
    "Birmingham, AL",
    "Salt Lake City, UT",
    "Grand Rapids, MI",
    "Huntsville, AL",
    "Spokane, WA",
    "Des Moines, IA",
    "Toledo, OH",
    "Akron, OH",
    "Madison, WI",
    "Little Rock, AR",
    "Providence, RI",
    "Jackson, MS",
    "Montgomery, AL",
    "Shreveport, LA",
    "Augusta, GA",
    "Columbus, GA",
    "Savannah, GA",
    "Chattanooga, TN",
    "Knoxville, TN",
    "Lexington, KY",
    "Louisville, KY",
    "Mobile, AL",
    "Tallahassee, FL",
    "Gainesville, FL",
    "Jacksonville, FL",
    "Tampa, FL",
    "St. Petersburg, FL",
    "Orlando, FL",
    "Miami, FL",
    "Fort Lauderdale, FL",
    "West Palm Beach, FL",
    "Baton Rouge, LA",
    "New Orleans, LA",
    "Lafayette, LA",
    "Shreveport, LA",
    "Bossier City, LA",
    "Alexandria, LA",
    "Lake Charles, LA",
    "Monroe, LA",
    "Houma, LA",
    "Kenner, LA",
    "Central, LA",
    "Sulphur, LA",
    "Laplace, LA",
    "Harvey, LA",
    "Marrero, LA",
    "Terrytown, LA",
    "Chalmette, LA",
    "Metairie, LA",
    "Slidell, LA",
    "Mandeville, LA",
    "Covington, LA",
    "Hammond, LA",
    "Ponchatoula, LA",
    "Amite, LA",
    "Independence, LA",
    "Kentwood, LA",
    "Franklinton, LA",
    "Bogalusa, LA",
    "Abbeville, LA",
    "Crowley, LA",
    "Eunice, LA",
    "Opelousas, LA",
    "Ville Platte, LA",
    "Mamou, LA",
    "Church Point, LA",
    "Rayne, LA",
    "Kaplan, LA",
    "Gueydan, LA",
    "Jennings, LA",
    "Welsh, LA",
    "Lake Arthur, LA",
    "Iowa, LA",
    "Roanoke, LA",
    "DeQuincy, LA",
    "Sulphur, LA",
    "Vinton, LA",
    "Westlake, LA",
    "Carlyss, LA",
    "Moss Bluff, LA",
    "Gillis, LA",
    "Ragley, LA",
    "DeRidder, LA",
    "Rosepine, LA",
    "Merryville, LA",
    "Pitkin, LA",
    "Elizabeth, LA",
    "Hornbeck, LA",
    "Anacoco, LA",
    "Leesville, LA",
    "New Llano, LA",
    "Fort Polk, LA",
    "Many, LA",
    "Zwolle, LA",
    "Noble, LA",
    "Converse, LA",
    "Pleasant Hill, LA",
    "Stanley, LA",
    "Fisher, LA",
    "Florien, LA",
    "Pleasant Hill, LA",
    "Converse, LA",
    "Noble, LA",
    "Zwolle, LA",
    "Many, LA",
    "Fort Polk, LA",
    "New Llano, LA",
    "Leesville, LA",
    "Anacoco, LA",
    "Hornbeck, LA",
    "Elizabeth, LA",
    "Pitkin, LA",
    "Merryville, LA",
    "Rosepine, LA",
    "DeRidder, LA",
    "Ragley, LA",
    "Gillis, LA",
    "Moss Bluff, LA",
    "Carlyss, LA",
    "Westlake, LA",
    "Vinton, LA",
    "Sulphur, LA",
    "DeQuincy, LA",
    "Roanoke, LA",
    "Iowa, LA",
    "Lake Arthur, LA",
    "Welsh, LA",
    "Jennings, LA",
    "Gueydan, LA",
    "Kaplan, LA",
    "Rayne, LA",
    "Church Point, LA",
    "Mamou, LA",
    "Ville Platte, LA",
    "Opelousas, LA",
    "Eunice, LA",
    "Crowley, LA",
    "Abbeville, LA",
    "Bogalusa, LA",
    "Franklinton, LA",
    "Kentwood, LA",
    "Independence, LA",
    "Ponchatoula, LA",
    "Hammond, LA",
    "Covington, LA",
    "Mandeville, LA",
    "Slidell, LA",
    "Metairie, LA",
    "Chalmette, LA",
    "Terrytown, LA",
    "Marrero, LA",
    "Harvey, LA",
    "Laplace, LA",
    "Sulphur, LA",
    "Central, LA",
    "Kenner, LA",
    "Houma, LA",
    "Monroe, LA",
    "Lake Charles, LA",
    "Alexandria, LA",
    "Bossier City, LA",
    "Shreveport, LA",
    "Lafayette, LA",
    "New Orleans, LA",
    "Baton Rouge, LA"
]

export const searchLocations = (query: string, limit: number = 10): string[] => {
    if (!query.trim()) {
        return POPULAR_LOCATIONS.slice(0, limit)
    }

    const lowercaseQuery = query.toLowerCase()

    // First, find exact matches
    const exactMatches = POPULAR_LOCATIONS.filter(location =>
        location.toLowerCase().includes(lowercaseQuery)
    )

    // Then find partial matches
    const partialMatches = POPULAR_LOCATIONS.filter(location =>
        location.toLowerCase().includes(lowercaseQuery) &&
        !exactMatches.includes(location)
    )

    // Combine and limit results
    return [...exactMatches, ...partialMatches].slice(0, limit)
}
